import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

for (const route of ['demo', 'privacy', 'terms']) {
  await mkdir(new URL(`../dist/${route}/`, import.meta.url), { recursive: true });
  await cp(new URL('../dist/index.html', import.meta.url), new URL(`../dist/${route}/index.html`, import.meta.url));
}
await cp(new URL('../dist/index.html', import.meta.url), new URL('../dist/404.html', import.meta.url));

// Vite fingerprints application entrypoints on every build. Generate the
// worker only after the emitted entrypoints are known, so an offline reload
// always has the exact JS and CSS required to render the cached document.
const dist = new URL('../dist/', import.meta.url);
const html = await readFile(new URL('index.html', dist), 'utf8');
const generatedAssets = [...html.matchAll(/(?:src|href)="(\/assets\/[^"?]+)"/g)].map((match) => match[1]);
const shell = [...new Set([
  '/',
  '/demo/',
  '/privacy/',
  '/terms/',
  '/?demo=1',
  ...generatedAssets,
  '/art/patch-spirit.webp',
  '/art/patchboard-social.png',
  '/apple-touch-icon.png',
  '/icon.svg',
  '/manifest.webmanifest',
])];
const cacheVersion = createHash('sha256').update(shell.join('\n')).digest('hex').slice(0, 12);

await writeFile(new URL('sw.js', dist), `/* Generated by scripts/postbuild.mjs; do not hand-edit. */
const CACHE = 'patchboard-shell-${cacheVersion}';
const SHELL = ${JSON.stringify(shell)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    // Some hosts add Vary: Origin to static assets. The install fetch has no
    // Origin header while a module request does, so ignore that transport-only
    // variance when looking up this same-origin shell asset.
    caches.match(event.request, { ignoreVary: true }).then((cached) => cached || fetch(event.request).then((response) => {
      if (response.ok && new URL(event.request.url).origin === self.location.origin) {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(event.request, copy));
      }
      return response;
    }).catch(() => event.request.mode === 'navigate' ? caches.match('/') : Response.error())),
  );
});
`);
